"""
系统常量定义
"""

# 支持的文件格式
SUPPORTED_DOCUMENT_FORMATS = [".docx", ".pdf", ".doc"]
SUPPORTED_IMAGE_FORMATS = [".jpg", ".jpeg", ".png", ".bmp", ".tiff"]

# 文档类型
DOCUMENT_TYPE_INSTRUCTION_BOOK = "instruction_book"
DOCUMENT_TYPE_RISK_MANAGEMENT = "risk_management"

DOCUMENT_TYPES = [
    DOCUMENT_TYPE_INSTRUCTION_BOOK,
    DOCUMENT_TYPE_RISK_MANAGEMENT
]

# 审核结果等级
SCORE_LEVEL_EXCELLENT = "excellent"  # 优秀 (>=0.9)
SCORE_LEVEL_GOOD = "good"           # 良好 (0.8-0.9)
SCORE_LEVEL_QUALIFIED = "qualified" # 合格 (0.7-0.8)
SCORE_LEVEL_NEED_IMPROVE = "need_improve"  # 待改进 (0.6-0.7)
SCORE_LEVEL_UNQUALIFIED = "unqualified"    # 不合格 (<0.6)

SCORE_LEVELS = [
    SCORE_LEVEL_EXCELLENT,
    SCORE_LEVEL_GOOD,
    SCORE_LEVEL_QUALIFIED,
    SCORE_LEVEL_NEED_IMPROVE,
    SCORE_LEVEL_UNQUALIFIED
]

# 分数阈值
SCORE_THRESHOLDS = {
    SCORE_LEVEL_EXCELLENT: 0.9,
    SCORE_LEVEL_GOOD: 0.8,
    SCORE_LEVEL_QUALIFIED: 0.7,
    SCORE_LEVEL_NEED_IMPROVE: 0.6,
    SCORE_LEVEL_UNQUALIFIED: 0.0
}

# 处理效率阈值（秒）
EFFICIENCY_EXCELLENT_THRESHOLD = 30
EFFICIENCY_GOOD_THRESHOLD = 60
EFFICIENCY_QUALIFIED_THRESHOLD = 120

# 最大文件大小（MB）
MAX_FILE_SIZE_MB = 50

# 批量处理限制
MAX_BATCH_FILES = 50

# 模型相关常量
DEFAULT_MAX_LENGTH = 512
DEFAULT_BATCH_SIZE = 16
DEFAULT_LEARNING_RATE = 2e-5

# API相关常量
DEFAULT_API_HOST = "0.0.0.0"
DEFAULT_API_PORT = 8000
DEFAULT_API_TIMEOUT = 300

# 日志级别
LOG_LEVEL_DEBUG = "DEBUG"
LOG_LEVEL_INFO = "INFO"
LOG_LEVEL_WARNING = "WARNING"
LOG_LEVEL_ERROR = "ERROR"
LOG_LEVEL_CRITICAL = "CRITICAL"

# 作业指导书必需章节
INSTRUCTION_BOOK_REQUIRED_SECTIONS = [
    "目录", "职责", "作业内容", "相关文件", "记录文件"
]

# 风险管控方案必需要素
RISK_MANAGEMENT_REQUIRED_ELEMENTS = [
    "人员密集型", "环境敏感", "市政管网", "围油设施"
]

# OCR引擎选项
OCR_ENGINE_PADDLEOCR = "paddleocr"
OCR_ENGINE_TESSERACT = "tesseract"

# 图像处理常量
IMAGE_RESIZE_MAX_SIZE = 1920
IMAGE_QUALITY_THRESHOLD = 0.8

# 错误码定义
ERROR_CODE_SUCCESS = 0
ERROR_CODE_FILE_NOT_FOUND = 1001
ERROR_CODE_UNSUPPORTED_FORMAT = 1002
ERROR_CODE_FILE_TOO_LARGE = 1003
ERROR_CODE_PARSING_ERROR = 1004
ERROR_CODE_MODEL_ERROR = 1005
ERROR_CODE_NETWORK_ERROR = 1006
ERROR_CODE_UNKNOWN_ERROR = 9999

# 错误消息
ERROR_MESSAGES = {
    ERROR_CODE_SUCCESS: "成功",
    ERROR_CODE_FILE_NOT_FOUND: "文件不存在",
    ERROR_CODE_UNSUPPORTED_FORMAT: "不支持的文件格式",
    ERROR_CODE_FILE_TOO_LARGE: "文件过大",
    ERROR_CODE_PARSING_ERROR: "文档解析失败",
    ERROR_CODE_MODEL_ERROR: "模型推理失败",
    ERROR_CODE_NETWORK_ERROR: "网络连接失败",
    ERROR_CODE_UNKNOWN_ERROR: "未知错误"
} 